accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetCompleteView, LogoutView

from accounts.views import LoginView, RegisterView, activate, PasswordResetView, PasswordResetConfirmView

app_name = "account"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("", include("social_django.urls", namespace="social")),
    path("register/", RegisterView.as_view(), name="register"),
    path("activate/<uidb64>/<token>/", activate, name="activate"),
    path("password_reset/", PasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/", PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/", PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("accounts.urls")),
    path("dashboard/", include("dashboard.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.urls import path, include

from dashboard.views import (
    Dashboard,
    InviteFriendView,
    PasswordChangeView,
    AccountSettings,
)

app_name = "dashboard"

urlpatterns = [
    path("", Dashboard.as_view(), name="dashboard"),
    path("invite_friend", InviteFriendView.as_view(), name="invite_friend"),
    path("settings/general/", AccountSettings.as_view(), name="account_settings"),
    path("settings/password_change/", PasswordChangeView.as_view(), name="password_change"),
    path("group/", include("groups.urls")),
    path("wallet/", include("wallet.urls")),
    path("expense/", include("expenses.urls")),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator
from django.db import models


class User(AbstractUser):
    email = models.EmailField(unique=True)
    wallet = models.DecimalField(default=0.00, max_digits=12, decimal_places=2, validators=[MinValueValidator(0.00)])

dashboard/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "email",
            "username",
        )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "email",
            "username",
        )


class SignUpForm(CustomUserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("first_name", "last_name", "username", "email", "password1", "password2")

accounts/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetConfirmView
from django.contrib import messages

from django.contrib.messages.views import SuccessMessageMixin

from config import settings
from accounts.forms import SignUpForm
from accounts.tokens import account_activation_token

User = get_user_model()


class LoginView(SuccessMessageMixin, LoginView):
    template_name = "registration/login.html"
    success_message = "login in successfully"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse(settings.LOGIN_REDIRECT_URL))
        return super(LoginView, self).get(request, *args, **kwargs)


class RegisterView(SuccessMessageMixin, CreateView):
    form_class = SignUpForm
    template_name = "registration/register.html"
    success_url = reverse_lazy("account:login")
    success_message = "Please confirm your email address to complete the registration"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse(settings.LOGIN_REDIRECT_URL))
        return super(RegisterView, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        current_site = get_current_site(self.request)
        mail_subject = "Activate your blog account."
        message = render_to_string(
            "registration/register_activate_email.html",
            {
                "user": user,
                "domain": current_site.domain,
                "protocol": self.request.scheme,
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "token": account_activation_token.make_token(user),
            },
        )
        to_email = form.cleaned_data.get("email")
        email = EmailMessage(mail_subject, message, to=[to_email])
        email.content_subtype = "html"
        email.send()
        messages.success(self.request, self.success_message)
        return HttpResponseRedirect(self.success_url)


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        message = "Thank you for your email confirmation. Now you can login your account."
        success = True
    else:
        message = "Activation link is invalid!"
        success = False
    return render(request, "registration/register_activate_complete.html", {"message": message, "success": success})


class PasswordResetView(PasswordResetView):
    template_name = "registration/password_reset_form.html"
    html_email_template_name = "registration/password_reset_email.html"
    success_url = reverse_lazy("account:password_reset_done")


class PasswordResetConfirmView(PasswordResetConfirmView):
    template_name = "registration/password_reset_confirm.html"
    success_url = reverse_lazy("account:password_reset_complete")

dashboard/views.py
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, UpdateView, View
from django.contrib.auth import get_user_model
from django.contrib.auth.views import PasswordChangeView
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import EmailMessage

from dashboard.utils import get_balance, get_total_debt, get_total_credit
from expenses.models import Share
from groups.models import Invite

User = get_user_model()


class Dashboard(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/dashboard.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context["balance"] = get_balance(self.request.user)
        context["credit"] = get_total_credit(self.request.user)
        context["debt"] = get_total_debt(self.request.user)
        context["spent"] = Share.objects.get_spent(self.request.user)
        context["share_per_group"] = Share.objects.get_group_most_share(self.request.user)
        context["invitations"] = Invite.objects.get_all_user_invitations(self.request.user).count()
        return context


class InviteFriendView(LoginRequiredMixin, View):
    def post(self, request):
        user = request.user
        current_site = get_current_site(self.request)
        mail_subject = "Activate your blog account."
        message = render_to_string(
            "dashboard/invite_email.html",
            {
                "user": user,
                "domain": current_site.domain,
                "protocol": self.request.scheme,
            },
        )
        to_email = request.POST.get("email")
        email = EmailMessage(mail_subject, message, to=[to_email])
        email.content_subtype = "html"
        email.send()
        messages.success(self.request, "an email sent to invite email.")
        return HttpResponseRedirect(reverse("dashboard:dashboard"))


class AccountSettings(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = get_user_model()
    template_name = "dashboard/account/account_settings.html"
    fields = ["first_name", "last_name", "username", "email"]
    success_message = "fields changed successfully"
    success_url = reverse_lazy("dashboard:account_settings")

    def get_object(self, queryset=None):
        return User.objects.get(pk=self.request.user.pk)


class PasswordChangeView(LoginRequiredMixin, SuccessMessageMixin, PasswordChangeView):
    template_name = "dashboard/account/password_change.html"
    success_url = reverse_lazy("dashboard:dashboard")
    success_message = "Password changed successfully"

templates/dashboard/account/account_settings.html
{% extends 'dashboard/account/base.html' %}
{% load widget_tweaks %}
{% load gravatar %}

{% block from %}
    <div class="tab-pane active">
        <div class="media">
            <a href="javascript: void(0);">
                <img src="{% gravatar_url user.email 64 %}"  class="rounded mr-75" alt="profile image" height="64" width="64">
            </a>
            <div class="media-body mt-25">
                <div class="col-12 px-0 d-flex flex-sm-row flex-column justify-content-start">
                    <a href="https://gravatar.com/" class="btn btn-sm btn-light-primary ml-50 mb-50 mb-sm-0">Upload new photo</a>
                </div>
                <p class="text-muted ml-1 mt-50"><small>use Gravatar.com To set new Profile Picture</small></p>
            </div>
        </div>
        <hr>
        <form method="post">
        {% csrf_token %}
            <div class="row">
                <div class="col-12">
                    <div class="form-group">
                        <div class="controls">
                            <label class="{% if form.first_name.errors %}text-danger{% endif %}" for="{{ form.first_name.id_for_label }}">First Name</label>
                            {% render_field form.first_name|add_class:"form-control" placeholder="First Name" %}
                            {% for error in form.first_name.errors %}
                                <div class="text-danger small">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group">
                        <div class="controls">
                            <label class="{% if form.last_name.errors %}text-danger{% endif %}" for="{{ form.last_name.id_for_label }}">Last Name</label>
                            {% render_field form.last_name|add_class:"form-control" placeholder="Last Name" %}
                            {% for error in form.last_name.errors %}
                                <div class="text-danger small">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group">
                        <div class="controls">
                            <label class="{% if form.username.errors %}text-danger{% endif %}" for="{{ form.username.id_for_label }}">Username</label>
                            {% render_field form.username|add_class:"form-control" placeholder="Username" %}
                            {% for error in form.username.errors %}
                                <div class="text-danger small">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group">
                        <div class="control">
                            <label class="{% if form.email.errors %}text-danger{% endif %}" for="{{ form.email.id_for_label }}">Email</label>
                            {% render_field form.email|add_class:"form-control" placeholder="Email" %}
                            {% for error in form.email.errors %}
                                <div class="text-danger small">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col-12">
                {% for error in form.non_field_errors %}
                    <div class="rounded bg-warning text-center text-white small" style="padding:4px;word-wrap: break-word">
                          <strong>&#9888;</strong> {{ error }}
                    </div>
                {% endfor %}
                </div>
                <div class="col-12 d-flex flex-sm-row flex-column justify-content-end">
                    <button type="submit" class="btn btn-primary glow mr-sm-1 mb-1">Save
                        changes</button>
                    <button type="reset" class="btn btn-light mb-1">Cancel</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/dashboard/account/base.html
{% extends 'dashboard/base.html' %}
{% block title %}
    Account Settings
{% endblock %}
{% block content %}
    <div class="content-header row">
                <div class="content-header-left col-12 mb-2 mt-1">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h5 class=" float-left pr-1 mb-0">Account Settings</h5>
                        </div>
                    </div>
                </div>
    </div>
    <div class="content-body">
                <!-- account setting page start -->
                <section id="page-account-settings">
                    <div class="row">
                        <div class="col-12">
                            <div class="row">
                                <!-- left menu section -->
                                {% url 'dashboard:account_settings' as general %}
                                {% url 'dashboard:password_change' as password_change %}
                                <div class="col-md-3 mb-2 mb-md-0 pills-stacked">
                                    <ul class="nav nav-pills flex-column">
                                        <li class="nav-item">
                                            <a class="nav-link d-flex align-items-center {% if request.path == general %}active{% endif %}"  href={{ general }}>
                                                <i class="bx bx-cog"></i>
                                                <span>General</span>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link d-flex align-items-center {% if request.path == password_change %}active{% endif %}"  href={{ password_change }}>
                                                <i class="bx bx-lock"></i>
                                                <span>Change Password</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                <!-- right content section -->
                                <div class="col-md-9">
                                    <div class="card">
                                        <div class="card-content">
                                            <div class="card-body">
                                                <div class="tab-content">
                                                    {% block from %}

                                                    {% endblock %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- account setting page ends -->
    </div>
{% endblock %}

templates/dashboard/account/password_change.html
{% extends 'dashboard/account/base.html' %}
{% load widget_tweaks %}

{% block from %}
    <div class="tab-pane active">
        <form method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-12">
                    <div class="form-group">
                        <div class="controls">
                            <label class="{% if form.old_password.errors %}text-danger{% endif %}" for="{{ form.old_password.id_for_label }}">Old Password</label>
                            {% render_field form.old_password|add_class:"form-control" placeholder="Old Password" %}
                            {% for error in form.old_password.errors %}
                                <div class="text-danger small">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group">
                        <div class="controls">
                            <label class="{% if form.new_password1.errors %}text-danger{% endif %}" for="{{ form.new_password1.id_for_label }}">New Password</label>
                            {% render_field form.new_password1|add_class:"form-control" placeholder="New Password" %}
                            {% for error in form.new_password1.errors %}
                                <div class="text-danger small">
                                    {{ error }}
                                </div>
                            {% endfor %}

                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group">
                        <div class="controls">
                            <label class="{% if form.new_password2.errors %}text-danger{% endif %}" for="{{ form.new_password2.id_for_label }}">Retype new Password</label>
                            {% render_field form.new_password2|add_class:"form-control" placeholder="Retype new Password" %}
                                {% for error in form.new_password2.errors %}
                                    <div class="text-danger small">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                        </div>
                    </div>
                    {% if form.new_password1.help_text %}
                    <div class="alert bg-rgba-warning alert-dismissible mt-2" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                        <p class="mb-0">
                            {{ form.new_password1.help_text|safe }}
                        </p>
                    </div>
                    {% endif %}

                </div>

                <div class="col-12 d-flex flex-sm-row flex-column justify-content-end">
                    <button type="submit" class="btn btn-primary glow mr-sm-1 mb-1">Save
                        changes</button>
                    <button type="reset" class="btn btn-light mb-1">Cancel</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}