config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("accounts.urls")),
    path("dashboard/", include("dashboard.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.urls import path, include

from dashboard.views import (
    Dashboard,
    InviteFriendView,
    PasswordChangeView,
    AccountSettings,
)

app_name = "dashboard"

urlpatterns = [
    path("", Dashboard.as_view(), name="dashboard"),
    path("invite_friend", InviteFriendView.as_view(), name="invite_friend"),
    path("settings/general/", AccountSettings.as_view(), name="account_settings"),
    path("settings/password_change/", PasswordChangeView.as_view(), name="password_change"),
    path("group/", include("groups.urls")),
    path("wallet/", include("wallet.urls")),
    path("expense/", include("expenses.urls")),
]

dashboard/models.py
from django.db import models

# Create your models here.

expenses/models.py
from decimal import Decimal

from django.db import models
from django.db.models import Q, F, Sum
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator

from groups.models import Group

User = get_user_model()


class ExpenseManager(models.Manager):
    def create_expense(self, data, creator):
        expense = self.create(
            description=data["description"],
            creator=creator,
            group=Group.objects.get(pk=data["group_pk"]),
            total_cost=Decimal(data["total_cost"]).quantize(Decimal(".00")),
        )
        for participant in data["participants"]:
            user = User.objects.get(email=participant[0])
            expense.participants.add(
                user,
                through_defaults={
                    "share": Decimal(participant[1]).quantize(Decimal(".00")),
                    "paid": Decimal(participant[2]).quantize(Decimal(".00")),
                },
            )
        return expense


# Create your models here.
class Expense(models.Model):
    description = models.TextField()
    participants = models.ManyToManyField(
        User, through="Share", related_name="participants", related_query_name="participants"
    )
    creator = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    group = models.ForeignKey(Group, null=True, on_delete=models.SET_NULL)
    created = models.DateTimeField(auto_now_add=True)
    total_cost = models.DecimalField(
        default=0.00, max_digits=12, decimal_places=2, validators=[MinValueValidator(0.00)]
    )

    objects = ExpenseManager()

    def get_debtors(self):
        return Share.objects.filter(expense=self, paid__lt=F("share")).order_by("user").values("user", "share", "paid")

    def get_creditors(self):
        return Share.objects.filter(expense=self, paid__gt=F("share")).order_by("user").values("user", "share", "paid")

    def get_totoal_transfer_amount(self):
        debtors = self.get_debtors()
        return sum([debtor["share"] - debtor["paid"] for debtor in debtors])

    def __str__(self):
        return self.description


class ShareManger(models.Manager):
    def get_spent(self, user):
        return self.filter(user=user).aggregate(Sum("share"))["share__sum"] or 0

    def get_group_most_share(self, user):
        expense_per_group = self.filter(user=user).values("expense__group").annotate(Sum("share"))
        expense_per_group = [
            (str(Group.objects.get(pk=_["expense__group"])), float(_["share__sum"])) for _ in expense_per_group
        ][:4]
        sum_expense_per_group = sum([_[1] for _ in expense_per_group])
        expense_per_group.append(("other", float(self.get_spent(user)) - sum_expense_per_group))
        return expense_per_group


class Share(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    expense = models.ForeignKey(Expense, on_delete=models.CASCADE)
    share = models.DecimalField(default=0.00, max_digits=12, decimal_places=2, validators=[MinValueValidator(0.00)])
    paid = models.DecimalField(default=0.00, max_digits=12, decimal_places=2, validators=[MinValueValidator(0.00)])

    objects = ShareManger()

    class Meta:
        unique_together = [["user", "expense"]]

dashboard/views.py
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, UpdateView, View
from django.contrib.auth import get_user_model
from django.contrib.auth.views import PasswordChangeView
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import EmailMessage

from dashboard.utils import get_balance, get_total_debt, get_total_credit
from expenses.models import Share
from groups.models import Invite

User = get_user_model()


class Dashboard(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/dashboard.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context["balance"] = get_balance(self.request.user)
        context["credit"] = get_total_credit(self.request.user)
        context["debt"] = get_total_debt(self.request.user)
        context["spent"] = Share.objects.get_spent(self.request.user)
        context["share_per_group"] = Share.objects.get_group_most_share(self.request.user)
        context["invitations"] = Invite.objects.get_all_user_invitations(self.request.user).count()
        return context


class InviteFriendView(LoginRequiredMixin, View):
    def post(self, request):
        user = request.user
        current_site = get_current_site(self.request)
        mail_subject = "Activate your blog account."
        message = render_to_string(
            "dashboard/invite_email.html",
            {
                "user": user,
                "domain": current_site.domain,
                "protocol": self.request.scheme,
            },
        )
        to_email = request.POST.get("email")
        email = EmailMessage(mail_subject, message, to=[to_email])
        email.content_subtype = "html"
        email.send()
        messages.success(self.request, "an email sent to invite email.")
        return HttpResponseRedirect(reverse("dashboard:dashboard"))


class AccountSettings(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = get_user_model()
    template_name = "dashboard/account/account_settings.html"
    fields = ["first_name", "last_name", "username", "email"]
    success_message = "fields changed successfully"
    success_url = reverse_lazy("dashboard:account_settings")

    def get_object(self, queryset=None):
        return User.objects.get(pk=self.request.user.pk)


class PasswordChangeView(LoginRequiredMixin, SuccessMessageMixin, PasswordChangeView):
    template_name = "dashboard/account/password_change.html"
    success_url = reverse_lazy("dashboard:dashboard")
    success_message = "Password changed successfully"

templates/dashboard/expense/accountancy.html
{% extends 'dashboard/base.html' %}
{% load widget_tweaks %}
{% load gravatar %}

{% block title %}
    accountancy
{% endblock %}
{% block content %}
    <section class="row">
        <div class="col-sm-12 col-md-6">
            <div class="card border-success" style="height:auto;">
                <div class="card-header">
                    <h2>you are owed</h2>
                </div>
                <ul class="list-group" style="padding: 15px">
                    {% for credit in credits %}
                        <li class="list-group-item  rounded bg-rgba-success"
                            style="margin-top:4px; padding: 5px">
                            <img class="round" src="{% gravatar_url credit.0.email 40 %}" alt="avatar"
                                 height="40" width="40">
                            <span class="ml-1"><b>{{ credit.0 }}</b></span>
                            <div class="badge badge-success mr-1 float-right font-medium-2" style="margin-top: 3px">
                                ${{ credit.1 }}</div>

                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="col-sm-12 col-md-6">
            <div class="card border-danger" style="height: auto;">
                <div class="card-header">
                    <h1>you owe</h1>
                    <div class="card-text">
                        <p>for settle up <b>click</b> on badge.</p>
                    </div>
                </div>

                <ul class="list-group" style="padding: 15px">
                    {% for debt in debts %}
                        <li class="list-group-item  rounded bg-rgba-danger"
                            style="margin-top:4px; padding: 5px">
                            <img class="round" src="{% gravatar_url debt.0.email 40 %}" alt="avatar"
                                 height="40" width="40">
                            <span class="ml-1"><b>{{ debt.0 }}</b></span>
                            <a class="badge badge-danger mr-1 float-right font-medium-2" style="margin-top: 3px" href="{% url 'dashboard:expense:settle_up' debt.0.pk %}">
                                ${{ debt.1 }}</a>

                        </li>
                    {% endfor %}
                </ul>

            </div>
        </div>
    </section>
{% endblock %}

templates/dashboard/expense/add_expense_base.html
{% extends 'dashboard/base.html' %}
{% load widget_tweaks %}

{% block title %}
    Add Expense
{% endblock %}

{% block css %}
    <style>
        .steps-form {
            display: table;
            width: 100%;
            position: relative;
        }

        .steps-form .steps-row {
            display: table-row;
        }

        .steps-form .steps-row:before {
            top: 14px;
            bottom: 0;
            position: absolute;
            content: " ";
            width: 100%;
            height: 1px;
            background-color: #ccc;
        }

        .steps-form .steps-row .steps-step {
            display: table-cell;
            text-align: center;
            position: relative;
        }

        .steps-form .steps-row .steps-step p {
            margin-top: 0.5rem;
        }

        .steps-form .steps-row .steps-step button[disabled] {
            opacity: 1 !important;
            filter: alpha(opacity=100) !important;
        }

        .steps-form .steps-row .steps-step .btn-circle {
            width: 30px;
            height: 30px;
            text-align: center;
            padding: 6px 0;
            font-size: 12px;
            line-height: 1.428571429;
            border-radius: 15px;
            margin-top: 0;
        }

        .circle-icon {
            background: #fdf9f9;
            padding: 10px;
            border-radius: 50%;
        }
    </style>
{% endblock %}

{% block content %}

    <div class="content-body">
        <!-- Form wizard with icon tabs section start -->
        <section id="icon-tabs">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Add an expense</h4>
                        </div>
                        <div class="card-content mt-2">
                            <div class="card-body">
                                {% include 'dashboard/expense/add_expense_step1_form.html' %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Form wizard with number tabs section end -->
    </div>
{% endblock %}

templates/dashboard/expense/add_expense_step1_form.html
{% load django_htmx %}
{% load widget_tweaks %}
{% django_htmx_script %}
<form class="form" hx-post="{% url 'dashboard:expense:add_expense_step' 2 %}" hx-target="this" hx-swap="outerHTML">
    {% csrf_token %}
    <!-- Stepper -->
    <div class="steps-form">
        <div class="steps-row setup-panel">
            <div class="steps-step">
                <i class="fa fa-receipt fa-fw circle-icon " style="color:#ffed00"></i>
            </div>
            <div class="steps-step">
                <i class="fa fa-pen fa-fw circle-icon" style="color:#5bc0de"></i>
            </div>
            <div class="steps-step">
                <i class="fa fa-check fa-fw circle-icon" style="color:#5bc0de"></i>
            </div>
        </div>
    </div>
    <div class="form-body" style="margin-top: 50px">
        <div class="row">
            <div class="col-md-6 col-12">
                <div class="form-group">
                    <label class="text-bold-600 {% if form.total_cost.errors %}text-danger{% endif %}"
                           for="{{ form.total_cost.id_for_label }}">Total Cost</label>
                    {% render_field form.total_cost|add_class:"form-control" placeholder="Total Cost" %}
                    {% for error in form.total_cost.errors %}
                        <div class="text-danger small">
                            &#215; {{ error }}
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-6 col-12">
                <label class="text-bold-600 {% if form.group.errors %}text-danger{% endif %}"
                       for="{{ form.group.id_for_label }}">Total Cost</label>
                {% render_field form.group|add_class:"form-control" placeholder="Total Cost" %}
                {% for error in form.group.errors %}
                    <div class="text-danger small">
                        &#215; {{ error }}
                    </div>
                {% endfor %}
            </div>
            <div class=" col-12">
                <div class="form-group">
                    <label class="text-bold-600 {% if form.description.errors %}text-danger{% endif %}"
                           for="{{ form.description.id_for_label }}">description</label>
                    {% render_field form.description|add_class:"form-control" placeholder="text" %}
                    {% for error in form.description.errors %}
                        <div class="text-danger small">
                            &#215; {{ error }}
                        </div>
                    {% endfor %}
                </div>
            </div>


            <div class="col-12 d-flex justify-content-end">
                <button type="submit" class="btn btn-success mr-1">Next</button>
            </div>
        </div>
    </div>
</form>

templates/dashboard/expense/add_expense_step2_form.html
{% load django_htmx %}
{% load widget_tweaks %}
{% django_htmx_script %}
<form class="form" hx-post="{% url 'dashboard:expense:add_expense_step' 3 %}" hx-target="this" hx-swap="outerHTML"
      id="form">
    {% csrf_token %}
    <!-- Stepper -->
    <div class="steps-form">
        <div class="steps-row setup-panel">
            <div class="steps-step">
                <i class="fa fa-receipt fa-fw circle-icon " style="color:#00fc4b"></i>
            </div>
            <div class="steps-step">
                <i class="fa fa-pen fa-fw circle-icon" style="color:#ffed00"></i>
            </div>
            <div class="steps-step">
                <i class="fa fa-check fa-fw circle-icon" style="color:#5bc0de"></i>
            </div>
        </div>
    </div>
    <div class="form-body" style="margin-top: 50px">
        <div class="row">
            {{ forms.management_form }}

            {% for form in forms %}
                <div class="col-md-8 col-12">
                    <div class="form-group">
                        <label class="text-bold-600 {% if form.user.errors %}text-danger{% endif %}"
                               for="{{ form.user.id_for_label }}">User</label>
                        {% render_field form.user|add_class:"form-control" placeholder="User" %}
                        {% for error in form.user.errors %}
                            <div class="text-danger small">
                                &#215; {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-md-2 col-12">
                    <label class="text-bold-600 {% if form.share.errors %}text-danger{% endif %}"
                           for="{{ form.share.id_for_label }}">Share</label>
                    {% render_field form.share|add_class:"form-control" placeholder="Share" %}
                    {% for error in form.share.errors %}
                        <div class="text-danger small">
                            &#215; {{ error }}
                        </div>
                    {% endfor %}
                </div>
                <div class="col-md-2 col-12">
                    <label class="text-bold-600 {% if form.paid.errors %}text-danger{% endif %}"
                           for="{{ form.paid.id_for_label }}">paid</label>
                    {% render_field form.paid|add_class:"form-control" placeholder="paid" %}
                    {% for error in form.paid.errors %}
                        <div class="text-danger small">
                            &#215; {{ error }}
                        </div>
                    {% endfor %}
                </div>

            {% endfor %}
            {% if error %}
                <div class="col-12">
                    <div class="alert bg-rgba-warning alert-dismissible mt-2" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                        <p class="mb-0">
                            {{ error }}
                        </p>
                    </div>
                </div>
            {% endif %}

            {#            <div class=" col-12">#}
            {#                <div class="form-group">#}
            {#                    <label class="text-bold-600 {% if form.description.errors %}text-danger{% endif %}"#}
            {#                           for="{{ form.description.id_for_label }}">description</label>#}
            {#                    {% render_field form.description|add_class:"form-control" placeholder="text" %}#}
            {#                    {% for error in form.description.errors %}#}
            {#                        <div class="text-danger small">#}
            {#                            &#215; {{ error }}#}
            {#                        </div>#}
            {#                    {% endfor %}#}
            {#                </div>#}
            {#            </div>#}


            <div class="col-12 d-flex justify-content-end">
                <button class="btn btn-primary mr-1" hx-get="{% url 'dashboard:expense:add_expense_step' 1 %}"
                        hx-target="form" hx-swap="outerHTML">Back
                </button>
                <button type="submit" class="btn btn-success mr-1">Next</button>
            </div>
        </div>
    </div>
</form>

templates/dashboard/expense/expense_list.html
{% extends 'dashboard/base.html' %}
{% load django_htmx %}
{% django_htmx_script %}
{% load mathfilters %}

{% block title %}
    expense List
{% endblock %}
{% block content %}
    <div class="content-header row h1">
        Expense List
    </div>
    <div class="content-body">
        <!-- users list start -->
        <section class="users-list-wrapper">
            <div class="users-list-table">
                <div class="card">
                    <div class="card-content">
                        <div class="card-body">
                            <!-- datatable start -->
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th></th>
                                        <th>id</th>
                                        <th>creator</th>
                                        <th>created date</th>
                                        <th>group</th>
                                        <th>total cost</th>
                                        <th>action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for expense in object_list %}
                                        <tr class="bg-dark">
                                            <td data-toggle="collapse" data-target="#group{{ expense.id }}"
                                                class="accordion-toggle">
                                                <button class="btn btn-default btn-xs"><i class="fa fa-eye fa-fw "></i>
                                                </button>
                                            </td>
                                            <td>{{ expense.id }}</td>
                                            <td>{{ expense.creator }}</td>
                                            <td>{{ expense.created }}</td>
                                            <td>{{ expense.group }}</td>
                                            <td>{{ expense.total_cost }}</td>
                                            <td>
                                                {% if request.user == expense.creator %}
                                                    <a href="{% url 'dashboard:expense:delete_expense' expense.pk %}"
                                                       class="btn btn-danger">Delete</a>
                                                {% endif %}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="12" class="hiddenRow" style="padding: 0 !important">
                                                <div class="accordian-body collapse" id="group{{ expense.id }}">
                                                    <section class="invoice-view-wrapper bg-dark">
                                                        <div class="card invoice-print-area">
                                                            <div class="card-body pb-0 mx-25">
                                                                <div class="row">
                                                                    <div class="col-lg-4 col-md-12">
                                                                        <span class="invoice-number mr-50">Expense#</span>
                                                                        <span>{{ expense.id }}</span>
                                                                    </div>
                                                                    <div class="col-lg-8 col-md-12">
                                                                        <div class="d-flex align-items-center justify-content-lg-end flex-wrap">
                                                                            <div class="mr-3">
                                                                                <small class="text-muted">Issue
                                                                                    Date:</small>
                                                                                <span>{{ expense.created }}</span>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <!-- description -->
                                                                <div class="row my-2 my-sm-3">
                                                                    <div class="col-sm-6 col-12 text-center text-sm-left order-2 order-sm-1">
                                                                        <h4 class="text-primary">Expense</h4>
                                                                        <span>{{ expense.description }}</span>
                                                                    </div>
                                                                </div>
                                                                <hr>
                                                                <!-- invoice address and contact -->
                                                                <div class="row invoice-info">
                                                                    <div class="col-sm-6 col-12 mt-1">
                                                                        <h6 class="invoice-from">Bill From</h6>
                                                                        <div class="mb-1">
                                                                            <span>Name: {{ expense.creator.get_full_name }}</span>
                                                                        </div>
                                                                        <div class="mb-1">
                                                                            <span>Username: {{ expense.creator.username }}</span>
                                                                        </div>
                                                                        <div class="mb-1">
                                                                            <span>Email: {{ expense.creator.email }}</span>
                                                                        </div>
                                                                    </div>
                                                                    <div class="col-sm-6 col-12 mt-1">
                                                                        <h6 class="invoice-to">Bill To</h6>
                                                                        <div class="mb-1">
                                                                            <span>{{ expense.group }}</span>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <hr>
                                                            </div>
                                                            <!-- product details table-->
                                                            <div class="invoice-product-details table-responsive">
                                                                <table class="table table-borderless mb-0">
                                                                    <thead>
                                                                    <tr class="border-0">
                                                                        <th scope="col">Email</th>
                                                                        <th scope="col">Share</th>
                                                                        <th scope="col">Paid</th>
                                                                        <th scope="col" class="text-right">Balance</th>
                                                                    </tr>
                                                                    </thead>
                                                                    <tbody>
                                                                    {% for share in expense.share_set.all %}
                                                                        <tr>
                                                                            <td>{{ share.user.email }}</td>
                                                                            <td>${{ share.share }}</td>
                                                                            <td>${{ share.paid }}</td>
                                                                            <td class="text-primary text-right font-weight-bold">
                                                                                ${{ share.paid|sub:share.share|floatformat:2 }} </td>
                                                                        </tr>
                                                                    {% endfor %}
                                                                    </tbody>
                                                                </table>
                                                            </div>

                                                            <!-- invoice subtotal -->
                                                            <div class="card-body pt-0 mx-25">
                                                                <hr>
                                                                <div class="row">
                                                                    <div class="col-4 col-sm-6 col-12 mt-75">
                                                                        <span class="invoice-title">Total Expense:&nbsp;</span>
                                                                        <span class="invoice-value">${{ expense.total_cost }}</span>

                                                                    </div>
                                                                </div>
                                                            </div>

                                                        </div>
                                                    </section>
                                                </div>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <!-- datatable ends -->
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Group list ends -->
    </div>


{% endblock %}