accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetCompleteView, LogoutView

from accounts.views import LoginView, RegisterView, activate, PasswordResetView, PasswordResetConfirmView

app_name = "account"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("", include("social_django.urls", namespace="social")),
    path("register/", RegisterView.as_view(), name="register"),
    path("activate/<uidb64>/<token>/", activate, name="activate"),
    path("password_reset/", PasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/", PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/", PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("accounts.urls")),
    path("dashboard/", include("dashboard.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.urls import path, include

from dashboard.views import (
    Dashboard,
    InviteFriendView,
    PasswordChangeView,
    AccountSettings,
)

app_name = "dashboard"

urlpatterns = [
    path("", Dashboard.as_view(), name="dashboard"),
    path("invite_friend", InviteFriendView.as_view(), name="invite_friend"),
    path("settings/general/", AccountSettings.as_view(), name="account_settings"),
    path("settings/password_change/", PasswordChangeView.as_view(), name="password_change"),
    path("group/", include("groups.urls")),
    path("wallet/", include("wallet.urls")),
    path("expense/", include("expenses.urls")),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, UpdateView, View
from django.contrib.auth import get_user_model
from django.contrib.auth.views import PasswordChangeView
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import EmailMessage

from dashboard.utils import get_balance, get_total_debt, get_total_credit
from expenses.models import Share
from groups.models import Invite

User = get_user_model()


class Dashboard(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/dashboard.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context["balance"] = get_balance(self.request.user)
        context["credit"] = get_total_credit(self.request.user)
        context["debt"] = get_total_debt(self.request.user)
        context["spent"] = Share.objects.get_spent(self.request.user)
        context["share_per_group"] = Share.objects.get_group_most_share(self.request.user)
        context["invitations"] = Invite.objects.get_all_user_invitations(self.request.user).count()
        return context


class InviteFriendView(LoginRequiredMixin, View):
    def post(self, request):
        user = request.user
        current_site = get_current_site(self.request)
        mail_subject = "Activate your blog account."
        message = render_to_string(
            "dashboard/invite_email.html",
            {
                "user": user,
                "domain": current_site.domain,
                "protocol": self.request.scheme,
            },
        )
        to_email = request.POST.get("email")
        email = EmailMessage(mail_subject, message, to=[to_email])
        email.content_subtype = "html"
        email.send()
        messages.success(self.request, "an email sent to invite email.")
        return HttpResponseRedirect(reverse("dashboard:dashboard"))


class AccountSettings(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = get_user_model()
    template_name = "dashboard/account/account_settings.html"
    fields = ["first_name", "last_name", "username", "email"]
    success_message = "fields changed successfully"
    success_url = reverse_lazy("dashboard:account_settings")

    def get_object(self, queryset=None):
        return User.objects.get(pk=self.request.user.pk)


class PasswordChangeView(LoginRequiredMixin, SuccessMessageMixin, PasswordChangeView):
    template_name = "dashboard/account/password_change.html"
    success_url = reverse_lazy("dashboard:dashboard")
    success_message = "Password changed successfully"

templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<!-- BEGIN: Head-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <meta name="description"
          content="Frest admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords"
          content="admin template, Frest admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="PIXINVENT">
    <title>{% block title %}Bdong{% endblock %}</title>
    <link rel="apple-touch-icon" href="{% static 'assets/images/ico/apple-icon-120.png' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/images/logo/loan.png' %}">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500,600%7CIBM+Plex+Sans:300,400,500,600,700"
          rel="stylesheet">

    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendors/css/vendors.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendors/css/tables/datatable/datatables.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendors/css/charts/apexcharts.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendors/css/extensions/dragula.min.css' %}">
    <!-- END: Vendor CSS-->

    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendors/css/extensions/toastr.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap-extended.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/colors.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/components.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/themes/dark-layout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/plugins/extensions/toastr.css' %}">
    <!-- END: Theme CSS-->

    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/core/menu/menu-types/vertical-menu.css' %}">
    {% block css %}

    {% endblock %}
    <!-- END: Page CSS-->

    <!-- BEGIN: Custom CSS-->
    <!-- END: Custom CSS-->

</head>
<!-- END: Head-->

<!-- BEGIN: Body-->

<body class="vertical-layout vertical-menu-modern dark-layout 2-columns  navbar-sticky footer-static  "
      data-open="click" data-menu="vertical-menu-modern" data-col="2-columns" data-layout="dark-layout">

<!-- BEGIN: Header-->
{% include 'dashboard/header.html' %}
<!-- END: Header-->


<!-- BEGIN: Main Menu-->
{% include 'dashboard/navbar.html' %}
<!-- END: Main Menu-->

<!-- BEGIN: Content-->
<div class="app-content content">
    <div class="content-overlay"></div>
    <div class="content-wrapper">
        {% block content %}
        {% endblock %}
    </div>
</div>
<!-- END: Content-->

<!-- demo chat-->

<div class="drag-target"></div>

<!-- BEGIN: Footer-->
{% include 'dashboard/footer.html' %}
<!-- END: Footer-->


<!-- BEGIN: Vendor JS-->
<script src="https://unpkg.com/htmx.org@1.6.0"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'assets/vendors/js/vendors.min.js' %}"></script>
<script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" data-auto-replace-svg="nest"></script>
<!-- BEGIN Vendor JS-->

<!-- BEGIN: Page Vendor JS-->
<script src="{% static 'assets/vendors/js/extensions/toastr.min.js' %}"></script>
<script src="{% static 'assets/vendors/js/charts/apexcharts.min.js' %}"></script>
<script src="{% static 'assets/vendors/js/extensions/dragula.min.js' %}"></script>
<!-- END: Page Vendor JS-->

<!-- BEGIN: Theme JS-->
<script src="{% static 'assets/js/scripts/configs/vertical-menu-dark.js' %}"></script>
<script src="{% static 'assets/js/core/app-menu.js' %}"></script>
<script src="{% static 'assets/js/core/app.js' %}"></script>
<script src="{% static 'assets/js/scripts/components.js' %}"></script>
<script src="{% static 'assets/js/scripts/footer.js' %}"></script>
<script src="{% static 'assets/js/scripts/extensions/toastr.js' %}"></script>
<!-- END: Theme JS-->

<!-- BEGIN: Page JS-->
{% block js %}

{% endblock %}
<!-- END: Page JS-->

<!-- Start: Message -->
<script>
    {% if messages %}
        {% for message in messages %}
            toastr.{{ message.tags }}("{{ message }}", {"closeButton": true})
        {% endfor %}
    {% endif %}
</script>
<!-- End: Message -->

</body>
<!-- END: Body-->

</html>

templates/dashboard/footer.html
<!-- BEGIN: Footer-->
<footer class="footer footer-static footer-dark">
    <p class="clearfix mb-0"><span class="float-left d-inline-block">2021 &copy; Bdong</span><span class="float-right d-sm-inline-block d-none">Created with<i class="bx bxs-heart pink mx-50 font-small-3"></i>by<a class="text-uppercase" href="https://1.envato.market/pixinvent_portfolio" target="_blank">Farhad</a></span>
        <button class="btn btn-primary btn-icon scroll-top" type="button"><i class="bx bx-up-arrow-alt"></i></button>
    </p>
</footer>
<!-- END: Footer-->

templates/dashboard/header.html
{% load static %}
{% load gravatar %}

<!-- BEGIN: Header-->
<div class="header-navbar-shadow"></div>
<nav class="header-navbar main-header-navbar navbar-expand-lg navbar navbar-with-menu fixed-top navbar-dark">
    <div class="navbar-wrapper">
        <div class="navbar-container content">
            <div class="navbar-collapse" id="navbar-mobile">
                <div class="mr-auto float-left bookmark-wrapper d-flex align-items-center">
                    <ul class="nav navbar-nav">
                        <li class="nav-item mobile-menu d-xl-none mr-auto"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ficon bx bx-menu"></i></a></li>
                    </ul>
                </div>
                <ul class="nav navbar-nav float-right">
                    <li class="nav-item d-none d-lg-block"><a class="nav-link nav-link-expand"><i class="ficon bx bx-fullscreen"></i></a></li>

{#                    <li class="dropdown dropdown-notification nav-item"><a class="nav-link nav-link-label" href="#" data-toggle="dropdown"><i class="ficon bx bx-bell bx-tada bx-flip-horizontal"></i><span class="badge badge-pill badge-danger badge-up">5</span></a>#}
{#                        <ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">#}
{#                            <li class="dropdown-menu-header">#}
{#                                <div class="dropdown-header px-1 py-75 d-flex justify-content-between"><span class="notification-title">7 new Notification</span><span class="text-bold-400 cursor-pointer">Mark all as read</span></div>#}
{#                            </li>#}
{#                            <li class="scrollable-container media-list"><a class="d-flex justify-content-between" href="javascript:void(0)">#}
{#                                    <div class="media d-flex align-items-center">#}
{#                                        <div class="media-left pr-0">#}
{#                                            <div class="avatar mr-1 m-0"><img src="../../../app-assets/images/portrait/small/avatar-s-11.jpg" alt="avatar" height="39" width="39"></div>#}
{#                                        </div>#}
{#                                        <div class="media-body">#}
{#                                            <h6 class="media-heading"><span class="text-bold-500">Congratulate Socrates Itumay</span> for work anniversaries</h6><small class="notification-text">Mar 15 12:32pm</small>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </a>#}
{#                                <div class="d-flex justify-content-between read-notification cursor-pointer">#}
{#                                    <div class="media d-flex align-items-center">#}
{#                                        <div class="media-left pr-0">#}
{#                                            <div class="avatar mr-1 m-0"><img src="../../../app-assets/images/portrait/small/avatar-s-16.jpg" alt="avatar" height="39" width="39"></div>#}
{#                                        </div>#}
{#                                        <div class="media-body">#}
{#                                            <h6 class="media-heading"><span class="text-bold-500">New Message</span> received</h6><small class="notification-text">You have 18 unread messages</small>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
{#                                <div class="d-flex justify-content-between cursor-pointer">#}
{#                                    <div class="media d-flex align-items-center py-0">#}
{#                                        <div class="media-left pr-0"><img class="mr-1" src="../../../app-assets/images/icon/sketch-mac-icon.png" alt="avatar" height="39" width="39"></div>#}
{#                                        <div class="media-body">#}
{#                                            <h6 class="media-heading"><span class="text-bold-500">Updates Available</span></h6><small class="notification-text">Sketch 50.2 is currently newly added</small>#}
{#                                        </div>#}
{#                                        <div class="media-right pl-0">#}
{#                                            <div class="row border-left text-center">#}
{#                                                <div class="col-12 px-50 py-75 border-bottom">#}
{#                                                    <h6 class="media-heading text-bold-500 mb-0">Update</h6>#}
{#                                                </div>#}
{#                                                <div class="col-12 px-50 py-75">#}
{#                                                    <h6 class="media-heading mb-0">Close</h6>#}
{#                                                </div>#}
{#                                            </div>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
{#                                <div class="d-flex justify-content-between cursor-pointer">#}
{#                                    <div class="media d-flex align-items-center">#}
{#                                        <div class="media-left pr-0">#}
{#                                            <div class="avatar bg-primary bg-lighten-5 mr-1 m-0 p-25"><span class="avatar-content text-primary font-medium-2">LD</span></div>#}
{#                                        </div>#}
{#                                        <div class="media-body">#}
{#                                            <h6 class="media-heading"><span class="text-bold-500">New customer</span> is registered</h6><small class="notification-text">1 hrs ago</small>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
{#                                <div class="cursor-pointer">#}
{#                                    <div class="media d-flex align-items-center justify-content-between">#}
{#                                        <div class="media-left pr-0">#}
{#                                            <div class="media-body">#}
{#                                                <h6 class="media-heading">New Offers</h6>#}
{#                                            </div>#}
{#                                        </div>#}
{#                                        <div class="media-right">#}
{#                                            <div class="custom-control custom-switch">#}
{#                                                <input class="custom-control-input" type="checkbox" checked id="notificationSwtich">#}
{#                                                <label class="custom-control-label" for="notificationSwtich"></label>#}
{#                                            </div>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
{#                                <div class="d-flex justify-content-between cursor-pointer">#}
{#                                    <div class="media d-flex align-items-center">#}
{#                                        <div class="media-left pr-0">#}
{#                                            <div class="avatar bg-danger bg-lighten-5 mr-1 m-0 p-25"><span class="avatar-content"><i class="bx bxs-heart text-danger"></i></span></div>#}
{#                                        </div>#}
{#                                        <div class="media-body">#}
{#                                            <h6 class="media-heading"><span class="text-bold-500">Application</span> has been approved</h6><small class="notification-text">6 hrs ago</small>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
{#                                <div class="d-flex justify-content-between read-notification cursor-pointer">#}
{#                                    <div class="media d-flex align-items-center">#}
{#                                        <div class="media-left pr-0">#}
{#                                            <div class="avatar mr-1 m-0"><img src="../../../app-assets/images/portrait/small/avatar-s-4.jpg" alt="avatar" height="39" width="39"></div>#}
{#                                        </div>#}
{#                                        <div class="media-body">#}
{#                                            <h6 class="media-heading"><span class="text-bold-500">New file</span> has been uploaded</h6><small class="notification-text">4 hrs ago</small>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
{#                                <div class="d-flex justify-content-between cursor-pointer">#}
{#                                    <div class="media d-flex align-items-center">#}
{#                                        <div class="media-left pr-0">#}
{#                                            <div class="avatar bg-rgba-danger m-0 mr-1 p-25">#}
{#                                                <div class="avatar-content"><i class="bx bx-detail text-danger"></i></div>#}
{#                                            </div>#}
{#                                        </div>#}
{#                                        <div class="media-body">#}
{#                                            <h6 class="media-heading"><span class="text-bold-500">Finance report</span> has been generated</h6><small class="notification-text">25 hrs ago</small>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
{#                                <div class="d-flex justify-content-between cursor-pointer">#}
{#                                    <div class="media d-flex align-items-center border-0">#}
{#                                        <div class="media-left pr-0">#}
{#                                            <div class="avatar mr-1 m-0"><img src="../../../app-assets/images/portrait/small/avatar-s-16.jpg" alt="avatar" height="39" width="39"></div>#}
{#                                        </div>#}
{#                                        <div class="media-body">#}
{#                                            <h6 class="media-heading"><span class="text-bold-500">New customer</span> comment recieved</h6><small class="notification-text">2 days ago</small>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </li>#}
{#                            <li class="dropdown-menu-footer"><a class="dropdown-item p-50 text-primary justify-content-center" href="javascript:void(0)">Read all notifications</a></li>#}
{#                        </ul>#}
{#                    </li>#}
                    <li class="dropdown dropdown-user nav-item"><a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
                            <div class="user-nav d-sm-flex d-none"><span class="user-name">{% if request.user.get_full_name %}{{ request.user.get_full_name }}{% else %}{{ request.user.username }}{% endif %}</span><span class="user-status text-muted">{{ request.user.email }}</span></div><span><img class="round" src="{% gravatar_url user.email 40 %}" alt="avatar" height="40" width="40"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right pb-0"><a class="dropdown-item" href="{% url 'dashboard:account_settings' %}"><i class="bx bx-user mr-50"></i> Edit Profile</a><a class="dropdown-item" href="{% url 'dashboard:group:invite_list' %}"><i class="bx bx-envelope mr-50"></i> Invitation</a>
                            <div class="dropdown-divider mb-0"></div><a class="dropdown-item" href="{% url 'account:logout' %}"><i class="bx bx-power-off mr-50"></i> Logout</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>
<!-- END: Header-->

templates/dashboard/invite_email.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>

<html>

<head>
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <style type="text/css">
        @media screen {
            @font-face {
                font-family: 'Lato';
                font-style: normal;
                font-weight: 400;
                src: local('Lato Regular'), local('Lato-Regular'), url(https://fonts.gstatic.com/s/lato/v11/qIIYRU-oROkIk8vfvxw6QvesZW2xOQ-xsNqO47m55DA.woff) format('woff');
            }

            @font-face {
                font-family: 'Lato';
                font-style: normal;
                font-weight: 700;
                src: local('Lato Bold'), local('Lato-Bold'), url(https://fonts.gstatic.com/s/lato/v11/qdgUG4U09HnJwhYI-uK18wLUuEpTyoUstqEm5AMlJo4.woff) format('woff');
            }

            @font-face {
                font-family: 'Lato';
                font-style: italic;
                font-weight: 400;
                src: local('Lato Italic'), local('Lato-Italic'), url(https://fonts.gstatic.com/s/lato/v11/RYyZNoeFgb0l7W3Vu1aSWOvvDin1pK8aKteLpeZ5c0A.woff) format('woff');
            }

            @font-face {
                font-family: 'Lato';
                font-style: italic;
                font-weight: 700;
                src: local('Lato Bold Italic'), local('Lato-BoldItalic'), url(https://fonts.gstatic.com/s/lato/v11/HkF_qI1x_noxlxhrhMQYELO3LdcAZYWl9Si6vvxL-qU.woff) format('woff');
            }
        }

        /* CLIENT-SPECIFIC STYLES */
        body,
        table,
        td,
        a {
            -webkit-text-size-adjust: 100%;
            -ms-text-size-adjust: 100%;
        }

        table,
        td {
            mso-table-lspace: 0pt;
            mso-table-rspace: 0pt;
        }

        img {
            -ms-interpolation-mode: bicubic;
        }

        /* RESET STYLES */
        img {
            border: 0;
            height: auto;
            line-height: 100%;
            outline: none;
            text-decoration: none;
        }

        table {
            border-collapse: collapse !important;
        }

        body {
            height: 100% !important;
            margin: 0 !important;
            padding: 0 !important;
            width: 100% !important;
        }

        /* iOS BLUE LINKS */
        a[x-apple-data-detectors] {
            color: inherit !important;
            text-decoration: none !important;
            font-size: inherit !important;
            font-family: inherit !important;
            font-weight: inherit !important;
            line-height: inherit !important;
        }

        /* MOBILE STYLES */
        @media screen and (max-width:600px) {
            h1 {
                font-size: 32px !important;
                line-height: 32px !important;
            }
        }

        /* ANDROID CENTER FIX */
        div[style*="margin: 16px 0;"] {
            margin: 0 !important;
        }
    </style>
</head>

<body style="background-color: #f4f4f4; margin: 0 !important; padding: 0 !important;">
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <!-- LOGO -->
        <tr>
            <td bgcolor="#000066" align="center">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                    <tr>
                        <td align="center" valign="top" style="padding: 40px 10px 40px 10px;"> </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td bgcolor="#000066" align="center" style="padding: 0px 10px 0px 10px;">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                    <tr>
                        <td bgcolor="#ffffff" align="center" valign="top" style="padding: 40px 20px 20px 20px; border-radius: 4px 4px 0px 0px; color: #111111; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 48px; font-weight: 400; letter-spacing: 4px; line-height: 48px;">
                            <h1 style="font-size: 48px; font-weight: 400; margin: 2px;">Join Bdong</h1> <img src="{{ protocol }}://{{ domain }}{% static 'assets/images/pages/register.png' %}" width="125" height="120" style="display: block; border: 0px;" />
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td bgcolor="#f4f4f4" align="center" style="padding: 0px 10px 0px 10px;">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                    <tr>
                        <td bgcolor="#ffffff" align="left" style="padding: 20px 30px 40px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px; text-align: center">
                            <p style="margin: 0;">
                            <div class="text-center">
                            {% blocktranslate %}You're receiving this email because somebody invited you to join Bdong {{ site_name }}.{% endblocktranslate %}
                            <br/>
                            <br/>
                            {% translate "Join us with link below." %}
                            <br/>
                            </div>
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td bgcolor="#ffffff" align="left">
                            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td bgcolor="#ffffff" align="center" style="padding: 20px 30px 60px 30px;">
                                        <table border="0" cellspacing="0" cellpadding="0">
                                            <tr>
                                                <td align="center" style="border-radius: 3px;" bgcolor="#000066"><a href="{% block reset_link %}{{ protocol }}://{{ domain }}{% url 'account:register' %}{% endblock %}" target="_blank" style="font-size: 20px; font-family: Helvetica, Arial, sans-serif; color: #ffffff; text-decoration: none; color: #ffffff; text-decoration: none; padding: 15px 25px; border-radius: 2px; border: 1px solid #000066; display: inline-block;">Join Bdong</a></td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>

    </table>
</body>

</html>